# -*- coding: utf-8 -*-
"""matchfactor1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zj91Qp3HDSi1cYujQpc1B_bIIhrfBuRM
"""

import streamlit as st


st.title("MATCH FACTOR")
st.markdown("---")
st.markdown("Match Factor merupakan kesesuaian antara unit Loading dengan unit Hauling pada Operasional Penambangan. Tujuannya adalah untuk menentukan Kombinasi alat kerja yang optimal serta memastikan operasional berjalan dengan Produktif dan Aman")
st.markdown("Seringkali terjadi di lapangan, Jumlah unit Hauling yang sudah tersetting namun masih terjadi waktu tunggu atau antrian pada unit hauling, sehingga harus terus di monitor secara periodik 2-3 jam untuk meminimalkan waktu tunggu ataupun antrian")
st.markdown("Pada kesempatan ini, diberikan parameter untuk memotiring secara periodik di lapangan secara langsung, dengan Settingan unit Loading dapat di sesuaikan sesuai EGI sebagai berikut, PC850, PC1250SP8, PC1250SP11R, PC2000SP8, PC200011R. Sedangankan untuk unit Hauling hanya untuk EGI HD785")


# Parameter MF
JumlahHD = st.number_input("Masukkan Jumlah HD785 (Jumlah):")
Spoting = st.number_input("Masukkan Waktu Spotting Time (Detik):")
CTPC = st.number_input("Masukkan Waktu Cycle Time PC (Detik):")
Passing = st.number_input("Masukkan Jumlah Passing PC (Jumlah):")
Speed = st.number_input("Masukkan Speed HD (KM/Jam):")
Jarak = st.number_input("Masukkan Jarak Front ke Disposal (KM):")
LST = st.number_input("Masukkan Waktu Loaded Stop Time (Menit):")
EST = st.number_input("Masukkan Waktu Empty Stop Time (Menit):")

# Validasi kecepatan tidak boleh nol
if Speed <= 0:
    st.error("Kecepatan HD tidak boleh nol!")
    Speed = st.number_input("Masukkan Kecepatan HD (KM/Jam): ")

# Validasi jarak tidak boleh nol
if Jarak <= 0:
    st.error("Jarak tidak boleh nol!")
    Jarak = st.number_input("Masukkan Jarak Front ke Disposal (KM): ")

# Konversi Parameter
Spoting1 = Spoting / 60
LoadingTime = (CTPC * Passing) / 60
WaktuCycle = (Jarak / Speed) * 60
WaktuCycleTotal = WaktuCycle * 2

# Formula MF
hasil = (JumlahHD * (LoadingTime + Spoting1)) / (Spoting1 + LoadingTime + WaktuCycleTotal + LST + EST)

st.markdown(f"Hasil Match Factor adalah {hasil:.2f}")

# Memeriksa Hasil MF
if 0.95 <= hasil <= 1:
    st.success("MF Good, Pertahankan Parameter! :)")
elif hasil < 0.95:
    # Menentukan jumlah HD yang dibutuhkan untuk mencapai hasil minimum 0.96
    jumlah_hd_rekomendasi = (0.96 * (Spoting1 + LoadingTime + WaktuCycleTotal + LST + EST)) / (LoadingTime + Spoting1)
    st.warning(f"Rekomendasi: Tingkatkan Jumlah HD785 menjadi minimal {jumlah_hd_rekomendasi:.2f} HD")
else:
    # Menentukan kecepatan HD yang dibutuhkan untuk mencapai hasil maksimum 1
    speed_rekomendasi = (JumlahHD * (LoadingTime + Spoting1)) / ((Spoting1 + LoadingTime + WaktuCycleTotal + LST + EST) - JumlahHD)
    st.warning(f"Rekomendasi: Kurangi Kecepatan HD785 menjadi maksimal {speed_rekomendasi:.2f} KM/Jam")