# -*- coding: utf-8 -*-
"""mfglr2_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LNvIizjtO70Z1udRhIkz4qlAkK9XQv7i
"""

import streamlit as st
import requests
from PIL import Image

# URL gambar di GitHub
image_url = "https://github.com/setyo-dwi-pratama/PROJECTPAMAMF/blob/main/LOGO%20PAMA%20MELESAT.jpg?raw=true"

# Mengunduh gambar
response = requests.get(image_url)
image = Image.open(response)

# Mengatur ukuran gambar
new_size = (150, 150)  # Ukuran yang diinginkan
resized_image = image.resize(new_size)

# Membuat Streamlit app
st.title("Resized Image")
st.image(resized_image, caption='Resized Image')

st.title("VALCONT PROGRAM")
st.write("PAMA BEKB")
st.write("---")
st.write("Valcont (Validation and Controlling) Program atau yang biasa kita kenal dengan Match Factor merupakan kesesuaian antara unit Loading dengan unit Hauling pada Operasional Penambangan. Tujuannya adalah untuk menentukan Kombinasi alat kerja yang optimal serta memastikan operasional berjalan dengan Produktif dan Aman")
st.write("Seringkali terjadi bahwa Jumlah unit Hauling yang sudah tersetting, namun dilapangan masih terdapat waktu tunggu pada unit loading ataupun antrian pada unit hauling, sehingga diperlukan untuk terus dicontrol maupun dimonitor secara periodik 2-3 jam, maka dengan adanya Valcont Program diharapkan dapat meminimalkan waktu tunggu ataupun antrian pada Operasional Tambang Site BEKB")
st.write("Dengan adanya Program ValCont ini juga, diharapkan dapat membantu semua pihak untuk turut serta melakukan Validasi dan Controling secara bersama demi terapainya target produksi")
st.write("---")
st.write("Diberikan parameter untuk memonitoring secara periodik di lapangan secara langsung, dengan Settingan unit Loading dapat di sesuaikan dengan EGI sebagai berikut : PC850, PC1250SP8, PC1250SP11R, PC2000SP8, PC200011R")
st.write("Sedangankan untuk unit Hauling hanya untuk EGI : HD785")
st.write("---")
st.write("Masukan Parameter")

# Parameter MF
JumlahHD = st.number_input("Masukkan Jumlah HD785 (Jumlah): ")
CTPC = st.number_input("Masukkan Waktu Cycle Time PC (Detik): ")
Passing = st.number_input("Masukkan Jumlah Passing PC (Jumlah): ")
CTHD = st.number_input("Masukkan Cycle Time HD (Dari keluar front sampai memasuki front kembali)(Menit): ")
Jarak = st.number_input("Masukkan Jarak Front ke Disposal (KM): ")

# Validasi jarak tidak boleh nol
if Jarak <= 0:
  st.write("Jarak tidak boleh nol!")
  Jarak = st.number_input("Masukkan Jarak Front ke Disposal (KM): ")

# Konversi Parameter
LoadingTime = (CTPC * Passing) / 60

# Formula MF
hasil = (JumlahHD * LoadingTime) / (CTHD)

st.write(f"Hasil Match Factor adalah {hasil:.2f}")

# Memeriksa Hasil MF
if 0.95 <= hasil <= 1:
  st.write("MF Good, Pertahankan Parameter! :)")
elif hasil < 0.95:
  # Menentukan jumlah HD yang dibutuhkan untuk mencapai hasil minimum 0.96
  jumlah_hd_rekomendasi = (0.96 * CTHD) / (LoadingTime)
  st.write(f"Rekomendasi: Tingkatkan Jumlah HD785 menjadi minimal {jumlah_hd_rekomendasi:.2f} HD")
else:
  # Menentukan jumlah HD yang dibutuhkan untuk mencapai hasil maksimum 1
  jumlah_hd2_rekomendasi = (1.00 * CTHD) / (LoadingTime)
  st.write(f"Rekomendasi: Kurangi Jumlah HD785 menjadi maksimal {jumlah_hd2_rekomendasi:.2f} HD")

#Maximal Productivity Excavator
HD785 = 42
PdtyJam = 60
RitPC = round((PdtyJam/LoadingTime),0)
MaxRitasiPC = RitPC*HD785
st.write(f"Productivity Maksimal Excavator berdasarkan Parameter diperoleh {MaxRitasiPC:.2f} Bcm/Jam")

#Maximal Productivity HD
MaxRitasiHD = MaxRitasiPC/JumlahHD
st.write(f"Productivity Maksimal HD785 berdasarkan Parameter diperoleh {MaxRitasiHD:.2f} Bcm/Jam")

#Mencari Speed Rata-Rata dari Parameter
Cthd1 = CTHD - 3
CTHDJAM = Cthd1/60
speed = (Jarak+Jarak)/(CTHDJAM)
st.write(f"Speed rata-rata berdasarkan Parameter diperoleh {speed:.2f} Km/Jam")