# -*- coding: utf-8 -*-
"""mfpama.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L5qbrHWePSCgbJNE3jfLbLaV3A6BnPvD
"""

import streamlit as st

st.title("MATCH FACTOR PAMA BEKB")


st.markdown("---")

# Parameter MF
JumlahHD = st.number_input("Masukkan Jumlah HD (Jumlah):")
Spoting = st.number_input("Masukkan Waktu Spotting Time (Detik):")
CTPC = st.number_input("Masukkan Waktu Cycle Time PC (Detik):")
Passing = st.number_input("Masukkan Jumlah Passing PC (Jumlah):")
Speed = st.number_input("Masukkan Speed HD (KM/Jam):")
Jarak = st.number_input("Masukkan Jarak Front ke Disposal (KM):")
Disposal = st.number_input("Masukkan Waktu di Disposal (Menit):")

# Konversi Parameter
Spoting1 = Spoting / 60
LoadingTime = (CTPC * Passing) / 60
WaktuCycle = (Jarak / Speed) * 60
WaktuCycleTotal = WaktuCycle * 2

# Formula MF
hasil = (JumlahHD * (LoadingTime + Spoting1)) / (Spoting1 + LoadingTime + WaktuCycleTotal + Disposal)

st.markdown(f"Hasilnya adalah {hasil:.2f}")

# Memeriksa Hasil MF
if 0.95 <= hasil <= 1:
    st.success("MF Good, Pertahankan Parameter! :)")
elif hasil < 0.95:
    # Menentukan jumlah HD yang dibutuhkan untuk mencapai hasil minimum 0.96
    jumlah_hd_rekomendasi = (0.96 * (Spoting1 + LoadingTime + WaktuCycleTotal + Disposal)) / (LoadingTime + Spoting1)
    st.warning(f"Rekomendasi: Tingkatkan Jumlah HD menjadi minimal {jumlah_hd_rekomendasi:.2f} HD")
else:
    # Menentukan kecepatan HD yang dibutuhkan untuk mencapai hasil maksimum 1
    speed_rekomendasi = (JumlahHD * (LoadingTime + Spoting1)) / ((Spoting1 + LoadingTime + WaktuCycleTotal + Disposal) - JumlahHD)
    st.warning(f"Rekomendasi: Kurangi Kecepatan HD menjadi maksimal {speed_rekomendasi:.2f} KM/Jam")